---
language: node_js

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ./node_modules/.bin/ember try "$EMBER_TRY_SCENARIO" test

env:
  - EMBER_TRY_SCENARIO="Ember 1.10.0"
  - EMBER_TRY_SCENARIO="Ember 1.11.1"
  - EMBER_TRY_SCENARIO="Ember Beta"
  - EMBER_TRY_SCENARIO="Ember Canary"

matrix:
  allow_failures:
    - env: EMBER_TRY_SCENARIO="Ember Canary"